# Generated by Django 4.1.7 on 2023-02-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='modified_date',
            new_name='updated_date',
        ),
    ]
